Models/Employee.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PLACEMENT_2.Models
{
    public class Employee
    {
        [Key]
       public int Id { get; set; }
        [Required]
        [Column(TypeName = "Varchar(50)")]
        public string Name { get; set; }
        [Required]
        [Column(TypeName = "Varchar(50)")]
        public string Email { get; set; }
        [Required]
        [Column(TypeName = "Varchar(20)")]
        public string ContactNumber { get; set; }
        [Required]
        [Column(TypeName = "Varchar(100)")]
        public string Address { get; set; }


    }
}

Models/ErrorViewModel.cs
namespace PLACEMENT_2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/department.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PLACEMENT_2.Models
{
    public class department
    {
        [Key]
        public int Id { get; set; }

        [Column(TypeName = "Varchar(50)")]
        public string DepartmentName { get; set; }

        //[Column(TypeName = "Varchar(50)")]
        //public string Email { get; set; }

        //[Column(TypeName = "Varchar(20)")]
        //public string ContactNumber { get; set; }

        //[Column(TypeName = "Varchar(100)")]
        //public string Address { get; set; }


    }
}

Models/departmentstaaf.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PLACEMENT_2.Models
{
    public class departmentstaaf
    {
        [Key]
        public int Id { get; set; }

        [Column(TypeName = "Varchar(50)")]
        public string DepartmentName { get; set; }

        //[Column(TypeName = "Varchar(50)")]
        //public string Email { get; set; }

        //[Column(TypeName = "Varchar(20)")]
        //public string ContactNumber { get; set; }

        //[Column(TypeName = "Varchar(100)")]
        //public string Address { get; set; }


    }
}

Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PLACEMENT_2.Models;

namespace PLACEMENT_2.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly DBContext _departmentDBContext;
        public DepartmentController (DBContext departmentDBContext)
            //upar vala constroctor h mera
        {
            _departmentDBContext= departmentDBContext;
        }
        public IActionResult Index()
        {
            var data = _departmentDBContext.Department.ToList();
            return View(data);  
        }

        //public IActionResult Update()
        //{
        //    return View();
        //}

        public IActionResult Department()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }
        //Create
        [HttpPost]
        public IActionResult Create(department Model)
        {
            _departmentDBContext.Department.Add(Model);
            _departmentDBContext.SaveChanges();
           // return RedirectToAction("Index");
            // return View();

          
                //modal validate
                if (ModelState.IsValid)
                {
                _departmentDBContext.Department.Add(Model);
                _departmentDBContext.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(Model);
                }



            }
        public IActionResult Update(int id)
        {
            return View(_departmentDBContext.Department.Where(a => a.Id == id).FirstOrDefault());
        }

        [HttpPost]
        //public IActionResult Update_Post(department emp)
        //{
        //    _departmentDBContext.Update(emp);
        //    _departmentDBContext.SaveChanges();
        //    return RedirectToAction("Index");
        //}


        public IActionResult Update(department updatemodel)
        {
            var old_student_entries = _departmentDBContext.Department.FirstOrDefault(e => e.Id == updatemodel.Id);
            _departmentDBContext.Entry(old_student_entries).CurrentValues.SetValues(updatemodel);
            _departmentDBContext.SaveChanges();
            return RedirectToAction("Index");
        }


        //[HttpPost]
        [ActionName("Delete")]
        public IActionResult Delete(int id)
        {
            var teacher = _departmentDBContext.Department.Where(a => a.Id == id).FirstOrDefault();
            _departmentDBContext.Department.Remove(teacher);
            _departmentDBContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using PLACEMENT_2.Models;

namespace PLACEMENT_2.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly DBContext dbContext;
        public EmployeeController(DBContext employeeDBContext)
        {
            dbContext = employeeDBContext;
        }
        public IActionResult Index()
        {
            var employee = dbContext.Employee.ToList();
            return View(employee);
        }

        public IActionResult CreateEmployee()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateEmployee(Employee Model)
        {
            //modal validate
            if (ModelState.IsValid)
            {
                dbContext.Employee.Add(Model);
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(Model);
            }
        }
        public IActionResult Update(int id)
        {
            return View(dbContext.Employee.Where(a => a.Id == id).FirstOrDefault());
        }
        [HttpPost]
        [ActionName("Update")]
        public IActionResult Update_Post(Employee emp)
        {
            dbContext.Employee.Update(emp);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        //[HttpPost]
        [ActionName("Delete")]
        public IActionResult Delete(int id)
        {
            var teacher = dbContext.Employee.Where(a => a.Id == id).FirstOrDefault();
            dbContext.Employee.Remove(teacher);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PLACEMENT_2.Models;
using System.Diagnostics;

namespace PLACEMENT_2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Department()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Department/Create.cshtml
<p>HeyyyyBroo</p>





@model department

@{
    // ViewData["Title"] = "Employee Page";
}
@* @model List<Employee> *@

@* <p>This is my CRUD operation page</p> *@

<!-- Employee Add Form -->
<div class="container bg-dark bg-opacity-25 p-4 rounded">
    <form asp-action="Create" asp-controller="Department" method="post" class="form">
        <div class="form-group">
            <label for="DepartmentName">DepartmentName</label>
            <input type="text" asp-for="DepartmentName" class="form-control"  />
            <span asp-validation-for="DepartmentName" class="text-danger"></span>

  @*           <span asp-validation-for="DepartmentName" class="text-danger"></span> *@

        </div>
       @*  <div class="form-group">
            <label for="Email">Email</label>
            <input type="email" asp-for="Email" class="form-control" required />
        </div>
        <div class="form-group">
            <label for="ContactNumber">Contact</label>
            <input type="text" asp-for="ContactNumber" maxlength="10    " class="form-control" required />
        </div>
        <div class="form-group">
            <label for="Address">Address</label>
            <input type="text" asp-for="Address" class="form-control" required />
        </div> *@
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>

Views/Department/DepartmentEmployee.cshtml
@model department
@{
    ViewData["Title"] = "Department Page";
}
@* @model List<Employee> *@

<p>This is my CRUD operation page</p>

<div class="container bg-dark bg-opacity-25 p-4 rounded">
    <form asp-action="Create" asp-controller="Department" method="post" class="form">
        <div class="form-group">
            <label for="Name">Name</label>
            <input type="text" asp-for="Id" class="form-control" required />
        </div>
         <div class="form-group">
            <label for="Email">Email</label>
            <input type="email" asp-for="DepartmentName" class="form-control" required />
       @*  </div>
        <div class="form-group">
            <label for="ContactNumber">Contact</label>
            <input type="text" asp-for="ContactNumber" maxlength="10    " class="form-control" required />
        </div>
        <div class="form-group">
            <label for="Address">Address</label>
            <input type="text" asp-for="Address" class="form-control" required /> *@ 
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>

Views/Department/Index.cshtml
@model List<department>



<p>This IS Department Page</p>

<a asp-area="" asp-controller="Department" asp-action="Create">Add</a>


<table class="table"
    <tr>
        <th>Id</th>
        <th>DepartmentName</th>
       @*  <th>IsActive</th>
        <th>CreateDate</th>
        <th>CreatedBy</th>
        <th>ModifiedAt</th>
        <th>Modifiedby</th> *@

</tr>

    @foreach (var data in Model)
    {
            <tr>
                    <td>@data.Id</td>
                     <td>@data.DepartmentName</td>
                    @* <td>@data.Email</td>
                    <td>@data.ContactNumber</td>
                    <td>@data.Address</td> *@
                    <td>
                          <a href="@Url.Action("Update","Department", new {ID = data.Id})">Edit</a>
                          <a href="@Url.Action("Delete","Department", new {ID = data.Id})" class="mb-lg-3">Delete</a>
                    </td>
            </tr>

    }
</table>

Views/Department/Update.cshtml
@model department

@{
    ViewData["Title"] = "Update Department Page";
}
@* @model List<Employee> *@

<p>Update Department</p>




    <form asp-action="Update" asp-controller="Department" method="post" class="form">
    <div class="container bg-dark bg-opacity-25 p-4 rounded">
        <div class="form-group">
            <label for="DepartmentName">DepartmentName</label>
            <input type="text" asp-for="DepartmentName" class="form-control" />
        </div> 
  
        <button type="submit" class="btn btn-primary">Update</button>

       </div>
    </form>

Views/Employee/CreateEmployee.cshtml
@model Employee

@{
    ViewData["Title"] = "Employee Page";
}
@* @model List<Employee> *@

<p>This is my CRUD operation page</p>

<!-- Employee Add Form -->
    <div class="container bg-dark bg-opacity-25 p-4 rounded">
    <form asp-action="CreateEmployee" asp-controller="Employee" method="post" class="form">
    <div class="form-group">
        <label for="Name">Name</label>
        <input type="text" asp-for="Name" class="form-control"  />
            <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Email">Email</label>
            <input type="email" asp-for="Email"  class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
            <label for="ContactNumber">ContactNumber</label>
            <input type="text" asp-for="ContactNumber" maxlength="10" minlength="10" pattern="[0-9]{10}" required class="form-control" title="Please enter exactly 10 digits." />

            <span asp-validation-for="ContactNumber" class="text-danger"></span>

    </div>
    <div class="form-group">
        <label for="Address">Address</label>
            <input type="text" asp-for="Address"  class="form-control"  />
            <span asp-validation-for="Address" class="text-danger"></span>

    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
</div>
 <table id="myTable" class="display">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        <!-- Data from ASP.NET will be rendered here -->
    </tbody>
</table>


    

Views/Employee/Index.cshtml
@{
    ViewData["Title"] = "Employee Page";
}
@model List<Employee>
@* <p>This is my crud operation page</p> *@

@* <button type="button">Click Me!</button> *@

<a asp-area="" asp-controller="Employee" asp-action="CreateEmployee">Add</a>

<table class="table"
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Email</th>
        <th>Contact</th>
        <th>Address</th>
        <th>Action</th>

</tr>

    @foreach(var data in Model)
    {
        <tr>
                <td>@data.Id</td>
                <td>@data.Name</td>
                <td>@data.Email</td>
                <td>@data.ContactNumber</td>
                <td>@data.Address</td>
                <td>
                      <a href="@Url.Action("Update","Employee", new {ID = data.Id})">Edit</a>
                      <a href="@Url.Action("Delete","Employee", new {ID = data.Id})" class="mb-lg-3">Delete</a>
                </td>
        </tr>
        
    }
</table>

Views/Employee/Update.cshtml
@model Employee

@{
    ViewData["Title"] = "Update Employee Page";
}
@* @model List<Employee> *@

<p>Update Employee</p>

<!-- Employee Add Form -->
<div class="container bg-dark bg-opacity-25 p-4 rounded">
    <form asp-action="Update" asp-controller="Employee" method="post" class="form">
        <div class="form-group">
            <label for="Name">Name</label>
            <input type="text" asp-for="Name" class="form-control" />
        </div>
        <div class="form-group">
            <label for="Email">Email</label>
            <input type="email" asp-for="Email" class="form-control" />
        </div>
        <div class="form-group">
            <label for="ContactNumber">Contact</label>
            <input type="text" asp-for="ContactNumber" maxlength="10" class="form-control" />
        </div>
        <div class="form-group">
            <label for="Address">Address</label>
            <input type="text" asp-for="Address" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
@* <!-- Employee Table -->
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Contact</th>
            <th>Address</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var data in Model)
        {
            <tr>
                <td>@data.Id</td>
                <td>@data.Name</td>
                <td>@data.Email</td>
                <td>@data.ContactNumber</td>
                <td>@data.Address</td>
                <td>
                    <a href="@Url.Action("AdminEdit", "Admin", new { ID = data.Id })">Edit</a>
                    <a href="@Url.Action("Delete", "Admin", new { ID = data.Id })" class="mb-lg-3">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
 *@

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Employee Page";
}

<div class="text-center">
    <h1 class="display-4"></h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PLACEMENT_2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PLACEMENT_2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PLACEMENT_2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>



    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
@*             &copy; 2024 - PLACEMENT_2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>

 *@            </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" rel="stylesheet">
    